name: porofolio
description: "A new Flutter project."
homepage: https://omarayman.github.io/porofolio/
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  url_launcher: ^6.1.10
  cached_network_image: ^3.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: "^0.14.4"

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

flutter_launcher_icons:
  image_path: "assets/images/profile.jpg"
  web:
    generate: true
    background_color: "#hexcode"
    theme_color: "#hexcode"
